version: '3.8'

services:
  honeypot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: alpha-honeypot
    ports:
      - "5000:5000"
    environment:
      - DEBUG=false
      - HOST=0.0.0.0
      - PORT=5000
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - RETRAIN_THRESHOLD=10
    volumes:
      # Persist data files
      - honeypot_data:/app/data
      # Optional: mount custom config
      # - ./custom.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
    networks:
      - honeypot-network

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: alpha-honeypot-proxy
    ports:
      - "80:80"
      - "443:443"    volumes:
      # Optional: mount custom nginx config
      # - ./nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./ssl:/etc/nginx/ssl:ro  # For HTTPS
    depends_on:
      - honeypot
    restart: unless-stopped
    networks:
      - honeypot-network
    profiles:
      - production

volumes:
  honeypot_data:
    driver: local

networks:
  honeypot-network:
    driver: bridge
